enum Routes{

  onboardingScreen,
  startScreen,
  homeScreen,
  resetPasswordScreen,
  verifyProfile,
  verifyPhoneNumber,
  verifyPhoneOtp,
  successScreen,
  verifyIdentity,
  verifyPaymentMethod,
  forgetPasswordScreen,
  accountSettingScreen,
  profileInformationScreen,
  addEducation,
  paymentsMethod,
  addSocialAccount,
  notifcationsScreen,
  bankAccountInfo,
  addExperienceScreen,
  changeWorkExperienceScreen,
  changedPasswordScreen,
  addSkillsScreen,
  changeAddSkillScreen,
  addResumeScreen,
  contactDetailsScreen,
  contactDetailsActiveScreen,
  feedBackScreen,
  loginScreen,
  signupScreen,


}