name: job_contracts
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # UI
  flutter_screenutil: ^5.9.3

    # State Management
  get_it: ^8.0.1
  provider: ^6.1.2

    # Services
  shared_preferences: ^2.3.2
  dio: ^5.7.0

  # Utils
  equatable: ^2.0.5
  go_router: ^14.2.2
  flutter_secure_storage: ^9.2.2

  url_launcher: ^6.1.12
  intl: ^0.18.1
  logger: ^2.0.1
  flutter_native_splash: ^2.4.4

  loader_overlay: ^4.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/
    - assets/fonts/
  fonts:
    - family: DomaineArrow
      fonts:
        - asset: assets/fonts/domaine_arrow/DomaineDispNar-Black.otf
          weight: 900
        - asset: assets/fonts/domaine_arrow/DomaineDispNar-Bold.otf
          weight: 700
        - asset: assets/fonts/domaine_arrow/DomaineDispNar-Extrabold.otf
          weight: 600
        - asset: assets/fonts/domaine_arrow/DomaineDispNar-Medium.otf
          weight: 500
        - asset: assets/fonts/domaine_arrow/DomaineDispNar-Regular.otf
          weight: 400
        - asset: assets/fonts/domaine_arrow/DomaineDispNar-Semibold.otf
          weight: 300

    - family: DMSans
      fonts:
        - asset: assets/fonts/dm_sans/DMSans-Black.ttf
          weight: 400
        - asset: assets/fonts/dm_sans/DMSans-Bold.ttf
          weight: 500
        - asset: assets/fonts/dm_sans/DMSans-ExtraBold.ttf
          weight: 600
        - asset: assets/fonts/dm_sans/DMSans-ExtraLight.ttf
          weight: 700
        - asset: assets/fonts/dm_sans/DMSans-ExtraLightItalic.ttf
          weight: 900






