name: job_contracts
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # UI
  flutter_screenutil: ^5.9.3

  # State Management
  get_it: ^8.0.1
  provider: ^6.1.2

  # Services
  shared_preferences: ^2.3.2
  dio: ^5.8.0+1

  # Utils
  equatable: ^2.0.5
  go_router: ^14.2.2
  flutter_secure_storage: ^9.2.2

  url_launcher: ^6.1.12
  intl: ^0.19.0
  logger: ^2.0.1
  flutter_native_splash: ^2.4.4
  easy_localization: ^3.0.7

  loader_overlay: ^4.0.3
  dropdown_search: ^6.0.2
  dropdown_textfield: ^1.2.0
  dotted_border: ^2.1.0
  file_picker: ^8.3.1
  flutter_rating_stars: ^1.1.0
  flutter_rating_bar: ^4.0.1
  pinput: ^5.0.1
  get: ^4.6.6
  iconsax: ^0.0.8
  fluttertoast: ^8.2.12
  flutter_svg: ^2.0.17
  smooth_page_indicator: ^1.2.1
  google_maps_flutter: ^2.12.1
  image_picker: ^1.1.2
  intl_phone_field: ^3.2.0
  simple_circular_progress_bar: ^1.0.2
  flutter_localization: ^0.3.2
  another_flushbar: ^1.12.30
  country_code_picker: ^3.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/
    - assets/fonts/
    - assets/icons/
    - assets/svg/
    - assets/languages/

  fonts:
    - family: DomaineArrow
      fonts:
        - asset: assets/fonts/domaine_arrow/DomaineDispNar-Black.otf
          weight: 900
        - asset: assets/fonts/domaine_arrow/DomaineDispNar-Bold.otf
          weight: 700
        - asset: assets/fonts/domaine_arrow/DomaineDispNar-Extrabold.otf
          weight: 600
        - asset: assets/fonts/domaine_arrow/DomaineDispNar-Medium.otf
          weight: 500
        - asset: assets/fonts/domaine_arrow/DomaineDispNar-Regular.otf
          weight: 400
        - asset: assets/fonts/domaine_arrow/DomaineDispNar-Semibold.otf
          weight: 300

    - family: DMSans
      fonts:
        - asset: assets/fonts/dm_sans/DMSans-Black.ttf
          weight: 400
        - asset: assets/fonts/dm_sans/DMSans-Bold.ttf
          weight: 500
        - asset: assets/fonts/dm_sans/DMSans_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/dm_sans/DMSans-ExtraLight.ttf
          weight: 700
        - asset: assets/fonts/dm_sans/DMSans-ExtraLightItalic.ttf
          weight: 900

    - family: Onest
      fonts:
        - asset: assets/fonts/onest/Onest-Black.ttf
          weight: 400
        - asset: assets/fonts/onest/Onest-Black.ttf
          weight: 500
        - asset: assets/fonts/onest/Onest-Black.ttf
          weight: 600
        - asset: assets/fonts/onest/Onest-Black.ttf
          weight: 700
        - asset: assets/fonts/onest/Onest-Black.ttf
          weight: 900






